stages:
  - steps:
      # TODO: Share volume between steps
      - volumes:
          - name: "repository"
            emptyDir: {}
        serviceAccountName: "automation"
        initContainers:
          - image: "governmentpaas/git-ssh"
            command: "git clone $(GIT_REPOSITORY_URL) /go/src/github.com/mxinden/automation && cd /go/src/github.com/mxinden/automation && git checkout $(GIT_SHA)"
            volumeMounts:
              - mountPath: /go/src/github.com/mxinden/automation
                name: "repository"
        containers:
          - image: "golang"
            command: "set -ex && go fmt . && git diff --exit-code && go test -v $(go list ./...) && go build"
            workingDir:  "/go/src/github.com/mxinden/automation"
            volumeMounts:
              - mountPath: "/go/src/github.com/mxinden/automation"
                name: "repository"
  - steps:
      - volumes:
          - name: "repository"
            emptyDir: {}
        serviceAccountName: "automation"
        initContainers:
          - image: "governmentpaas/git-ssh"
            command: "git clone $(GIT_REPOSITORY_URL) /go/src/github.com/mxinden/automation && cd /go/src/github.com/mxinden/automation && git checkout $(GIT_SHA)"
            volumeMounts:
              - mountPath: /go/src/github.com/mxinden/automation
                name: "repository"
          - image: "golang"
            command: "set -ex && go build"
            workingDir:  "/go/src/github.com/mxinden/automation"
            volumeMounts:
              - mountPath: "/go/src/github.com/mxinden/automation"
                name: "repository"
        containers:
          - image: "docker:dind"
            workingDir:  "/go/src/github.com/mxinden/automation"
            volumeMounts:
              - mountPath: "/go/src/github.com/mxinden/automation"
                name: "repository"
            command: 'dockerd-entrypoint.sh & docker login -u=mxinden+automation -p=$(QUAY_AUTOMATION_ROBOT_PASSWORD) quay.io && docker build -t quay.io/mxinden/automation:$(GIT_SHA) . && docker push quay.io/mxinden/automation:$(GIT_SHA)'
            securityContext:
              privileged: true
            env:
              - name: QUAY_AUTOMATION_ROBOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: quay-automation-robot
                    key: QUAY_AUTOMATION_ROBOT_PASSWORD
