# This role binding allows "jane" to read pods in the "default" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: automation
  namespace: automation
subjects:
- kind: ServiceAccount
  name: automation
  namespace: automation
roleRef:
  kind: Role
  name: automation
  apiGroup: rbac.authorization.k8s.io
